import type { Metadata } from "next";
import "./globals.css";  // Keep other custom styles if needed.
import AddBootstrap from "./AddBootstrap";
import  "bootstrap/dist/css/bootstrap.min.css"

export const metadata: Metadata = {
  title: "Alberta",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
       
      </head>
      <body>
      <AddBootstrap />
        {children}
      </body>
    </html>
  );
}
