import type { Metadata } from "next";
import "./globals.css";  // Keep other custom styles if needed.
import AddBootstrap from "./AddBootstrap";
import  "bootstrap/dist/css/bootstrap.min.css"

export const metadata: Metadata = {
  title: "Alberta",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css" />
      <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>
      </head>
      <body>
      <AddBootstrap />
        {children}
      </body>
    </html>
  );
}
